### ISSUE TITLE
alpha mask or cutout object support request

### ISSUE THREAD

**Issue by weirdouncle** [Arvtesh/UnityFx.Outline#10]
Im using URP and a cutout object looks like this

it will be perfect like the right pic, and thanks for all your works

![TIM图片20200729095437](https://user-images.githubusercontent.com/12009458/88747809-2088a080-d182-11ea-8980-8da3e65fc205.png)

**Comment by Arvtesh** [comment]
Thank you for the request. I'm going to look into this when I have time. Hopefully it won't take too long.

**Comment by weirdouncle** [comment]
hi, I'd tried and succeed.
OutlineRenderer.cs line 338 change to "_commandBuffer.DrawRenderer(r, _resources.TmpMaterials[j], j);"
I think there should be a tag or mark to the tranparent object to choose the renderer method for better performance

**Comment by Arvtesh** [comment]
@weirdouncle I've just pushed alpha testing support to `develop`, so next release of the library will support this feature. Your fix might work in some cases, but it's unreliable. The correct solution is adding alpha testing support to the render shader and do some additional setup in `OutlineRenderer`. Hope this helps.
