### ISSUE TITLE
Merge objects in the same layer

### ISSUE THREAD

**Issue by Noxalus** [Arvtesh/UnityFx.Outline#12]
Hello!

I just discovered your work, and it seems pretty neat!

I would like to use this outline effect for my personal project to draw outline around multiple floor tiles as post process, and it seems pretty suitable for this purpose.

But, as each tile is a specific GameObject, I would like to avoid outlines between two tiles side by side and only have the outline around them.

Here is an example of what I would like with 2 cubes:

When they are not side by side:
![image](https://user-images.githubusercontent.com/1321964/91424673-648ec400-e85a-11ea-9905-cb87935b32e9.png)

When they are side by side:
![image](https://user-images.githubusercontent.com/1321964/91425044-eaab0a80-e85a-11ea-9f36-710111b14b17.png)

Is there an easy way to do that?

Thanks in advance for your answer! 😄

**Comment by Arvtesh** [comment]
Hello @Noxalus, nice to meet you! Try making all the cubes children of another game object, and then only draw outlines for the parent game object.

**Comment by Noxalus** [comment]
Wow, very nice! 👍 

Thank you so much for your help and for this tool, and sorry for the dumb question :/

**Comment by Noxalus** [comment]
I re-open this issue quickly as it's related, but if I have my parent game object in the outline effect, it will outline the children merging them properly. But if I add a new child to this parent, it won't be taken into account 😞 

Do you know why? Do I have to call a method to refresh the outline effect? 🤔

**Comment by Arvtesh** [comment]
If you're using `OutlineBehaviour`, there is `Update renderers` flag you can set in inspector.

**Comment by Avol** [comment]
Would be cool to have a feature to merge all outlines into single one without having to layer with parent game object. I have an issue where many game objects move around and storing them under same parent would cause many transform problems. For example all objects within one OutlineLayer coul merge as if it were under 1 parent gameobject?

**Comment by Arvtesh** [comment]
Seems an easy enhancement, I'm scheduling this for next release.

**Comment by Avol** [comment]
Awesome! This will save a lot of time and performance issues for my project!
