### ISSUE TITLE
Remove object from layer?

### ISSUE THREAD

**Issue by Noxalus** [Arvtesh/UnityFx.Outline#15]
Hello!

From the documentation, there is an example of how to add _GameObject_ to a specific layer from an _OutlineEffect_ component:

```csharp
var outlineEffect = Camera.main.GetComponent<OutlineEffect>();
outlineEffect.AddGameObject(myGo);
```

My question is: how can we remove this _GameObject_ from the outline effect when we don't want the outline anymore?

In my case, I would like to outline the object when it's selected, and hide the outline if it's not selected anymore. 

It couldn't be needed to have a method like this to do what I want, but I don't know how to do it 🤔 

Thanks in advance for your help!

**Comment by Arvtesh** [comment]
Adding a game object to outline effect like that actually adds it to the 1st layer of the attached outline layer collection. So what you could do to remove it is:
`outlineEffect.OutlineLayers[0].Remove(myGo);`

**Comment by Noxalus** [comment]
Thanks a lot for your answer! I didn't saw the propery for the _OutlineLayer_ from the _OutlineEffect_ class. 

Thank you very much for the commit too, it still makes sense to have a method to inverse the `AddGameObject` action. 👍
