### ISSUE TITLE
Outlines only work in editor

### ISSUE THREAD

**Issue by YahkubR** [Arvtesh/UnityFx.Outline#16]
Hello, i'm experiencing this odd issue where the outline only appears in scene view and not game.  In-game it goes pure white.
<img src="https://user-images.githubusercontent.com/51926008/92522110-4c209100-f1ec-11ea-990b-ef573cefa7da.png" width="300" >
<img src="https://user-images.githubusercontent.com/51926008/92522174-6490ab80-f1ec-11ea-9a10-98b6468efb1a.png" width="200" >
<img src="https://user-images.githubusercontent.com/51926008/92522210-6d817d00-f1ec-11ea-9ce1-983877e903cf.png" width="200" >

Any ideas what might be causing this?

Using        :   
Unity             2020.1.4f1 
Toolkit           0.8.0
Toolkit URP   0.1.0

**Comment by Arvtesh** [comment]
Sorry for not answering earlier. I'll take a look at the issue as soon as I have time.

**Comment by YahkubR** [comment]
Not a problem. Appreciate you taking a look :)

**Comment by Arvtesh** [comment]
Hm, work for me on 2020.1.4. Which platform is it? Could you test it on the example scene of the UnityFx.Outline.URP (from the github)? Or you can give me a sample project to investigate further.

**Comment by YahkubR** [comment]
heres a basic empty URP project where I'm seeing the issue.
http://www.mediafire.com/file/20h4arfuzz0rdzf/file

perhaps I'm just not configuring something right...

**Comment by Arvtesh** [comment]
The problem appears to be MSAA enabled in URP quality settings.

**Comment by YahkubR** [comment]
Thanks!  Just did a double check and the only thing causing it is the depth testing flag.  Appreciate the assistance.
