### ISSUE TITLE
Lot of compile-time errors.

### ISSUE THREAD

**Issue by VayKekaz** [Arvtesh/UnityFx.Outline#17]
![image](https://user-images.githubusercontent.com/61301078/92925315-001b5980-f443-11ea-8917-450165b37f0c.png)
using 2020.1.4f1

**Comment by Arvtesh** [comment]
HDRP is not supported currently. This is work in progress code.

**Comment by VayKekaz** [comment]
> HDRP is not supported currently. This is work in progress code.
but there are compile errors everywhere, not only in Outline.HDRP folder
> Also please keep in mind there are 4 unity projects in the repo.
it produces errors on other folders?

**Comment by Arvtesh** [comment]
What I mean is you cannot just put the repo into your Unity Assets folder. It is not supposed to work this way. Please use UPM to install the packages you need.
