### ISSUE TITLE
Screen turning black in URP

### ISSUE THREAD

**Issue by LucaBGt** [Arvtesh/UnityFx.Outline#20]
Hi! Not sure if I just did something wrong or if it's the add-ons fault, but here goes:
Using URP, I assigned a Camera the "Outline Effect" script and added the Render Asset to the forward renderer. Now, when I play my scene, this happens:

<img width="767" alt="Bildschirmfoto 2020-10-17 um 09 03 08" src="https://user-images.githubusercontent.com/32401333/96330696-9dc40300-1057-11eb-9abe-a9ecbea8c275.png">

My Particle System is visible, but the rest of the screen is completely black and the cube object to the right generates this weird white ghost of itself that moves relative to the object, but not at its actual position. This also happens with the demo scene, by the way.
Any help would be really great, and thanks for this amazing asset, too!

EDIT:
So, I got an error that the "Outline Effect" works ONLY in the built-in render pipeline, so now all that's enabled in my project is the Scripteable Render Feature. No errors, but also no outlines. I guess one problem solved and another one opened, because I'm not sure what to do know.

**Comment by Arvtesh** [comment]
There is an outline package specifically for URP, which you should use instead. Please refer to the readme file.
