### ISSUE TITLE
InvalidCastException when entering play mode

### ISSUE THREAD

**Issue by Vikesz12** [Arvtesh/UnityFx.Outline#25]
Hi!
Every time I enter play mode the following exception is thrown:

![image](https://user-images.githubusercontent.com/24491701/102601921-18290600-4121-11eb-9697-0df04d2f1691.png)
It doesn't matter if I use the layers or not I'm even getting the error when using no outline in the scene at all.
Unity version is 2020.1.17f1

**Comment by Arvtesh** [comment]
I cannot reproduce it on my side. Could you give more info on the issue? Did you try deleting Library folder and re-importing your project?

**Comment by Vikesz12** [comment]
It disappeared, on my end too, so it must have been a problem with our project, 
Thanks for looking into it anyways.
