### ISSUE TITLE
does it work on urp project?

### ISSUE THREAD

**Issue by wtksana** [Arvtesh/UnityFx.Outline#3]
i use unity 2020.1b urp project

my workflow

1.only import the UnityFx.Outline package.
2.add OutlineEffect component to my main camera.
3.add MyOutlineEffect compoent to my main camera. the code:

```
    public class SelectionIndicator : MonoBehaviour{
        [SerializeField] private GameObject selectedGO;

        void Start(){
            var outlineEffect = Camera.main.GetComponent<OutlineEffect>();
            var layer = new OutlineLayer("MyOutlines") {
                OutlineColor = Color.red, OutlineWidth = 7, OutlineMode = OutlineMode.Blurred
            };

            layer.Add(selectedGO);

            outlineEffect.OutlineLayers.Add(layer);
        }
    }
```

the `selectedGO` did not have outline effect in play mode

does my operation correct?

sorry for my bad english.

thanks.

**Comment by abogarsukov** [comment]
URP uses its own post-processing stack, so `OutlineBehaviour` and `OutlineEffect` most likely will not work with it (they are for built-in RP). URP [does not allow](https://forum.unity.com/threads/post-processing-and-urp-the-plan.795456/page-3#post-5466441) custom post-effects at the moment. They might add this (or at least support for post-processing stack v2) for 2019.4+. I guess the package will be patched than.

That said, it should be quite easy to adapt the package to any post-processing stack. See the [README](https://github.com/Arvtesh/UnityFx.Outline/blob/master/README.md) *Extensibility* section.

**Comment by Arvtesh** [comment]
Your code looks valid. As stated above both `OutlineBehaviour` and `OutlineEffect` are for built-in render pipeline. They might not work for URP/HDRP. That said, I'm going to release packages with outline implementation for:
- [Post-processing stack v2](https://docs.unity3d.com/Packages/com.unity.postprocessing@2.3/manual/index.html);
- [URP](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@8.0/manual/index.html);
- [HDRP](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@8.0/manual/index.html).

There is no ETA yet though.

**Comment by wtksana** [comment]
thank you for your reply
