### ISSUE TITLE
[BUG] Enable Depth Testing breaks outline in SceneView

### ISSUE THREAD

**Issue by STARasGAMES** [Arvtesh/UnityFx.Outline#31]
Hi
Great plugin! Very simple to use! 
But I faced an issue with Enable Depth Testing and Scene View:
![image](https://user-images.githubusercontent.com/23558898/126868192-c16dc3bd-5bfc-48b3-b34d-384a03402d62.png)

Looks like Enable Depth Testing breaks the outline effect in SceneView. Unity 2019.4.22f1. Using OutlineBehaviour component.
There are also warnings in the console:
```
CommandBuffer: built-in render texture type 3 not found while executing OutlineBehaviour - basket (SetRenderTarget depth buffer)
UnityEngine.GUIUtility:ProcessEvent (int,intptr)
```

The main intention to migrate to this asset was the Depth Testing, and in Game View it works like a charm! Thanks!

**Comment by STARasGAMES** [comment]
Hmmm, I'm using Post Processing Stack v2, maybe this causing the issue. But again, in GameView it's fine

**Comment by Arvtesh** [comment]
Thanks for the report, I'll look into it.

**Comment by Arvtesh** [comment]
OutlineBehaviour is designed for built-in pipeline only. It is not compatible with Post Processing stack v2 and URP/HDRP. There is a dedicated package for Post Processing stack.

**Comment by STARasGAMES** [comment]
> It is not compatible with Post Processing stack v2

But I'm using OutlineBehaviour with PPSv2 and it works fine :)

Ok, I got it. 

I just don't want to add a new image effect to dozens of profiles I already have, so I will stick around with OutlineBehaviour for now. Thanks for the reply!
