### ISSUE TITLE
Outline doesn't work in scene with no skybox. Built-in RP. OutlineBehaviour

### ISSUE THREAD

**Issue by STARasGAMES** [Arvtesh/UnityFx.Outline#34]
Sorry for creating so many issues :)

If skybox material isn't set here:
![image](https://user-images.githubusercontent.com/23558898/126877854-02e0287c-41e0-4d4f-b47d-1c6c31bac3cb.png)

then outline won't work. Most likely because `AfterSkybox` CameraEvent is never occurring. 

I know that I can choose CameraEvent on OutlineBehaviour, and choosing `CameraEvent.AfterForwardOpaque` works fine for me. But this is only for now...
Are there any downsides to using `AfterForwardOpaque` versus `AfterSkybox`?

**Comment by Arvtesh** [comment]
That's weird. Will check. Thanks for the report.

**Comment by Arvtesh** [comment]
Hm. Unity seems to changes skybox render order depending on its settings:
1) It the material is set, it is rendered after geometry;
2) If no material is set, it seems to be rendered on the very start on the rendering cycle, when it's too early to render outline.

The solution is to change RenderEvent value. There should not be any downsides - it's just render order. If it looks correct, it's OK.
