### ISSUE TITLE
Running an outline on every object?

### ISSUE THREAD

**Issue by LeytonViner** [Arvtesh/UnityFx.Outline#36]
There doesn't seem to be a way to outline every object in the scene using the post processing filter. Am I missing something?

**Comment by Arvtesh** [comment]
Please give more details. Which package are you using? If it is post processing v2, you have to manually add game objects you want to be outlined into OutlineLayerCollection scriptable object. You can just add root of your hierarchy and have all of its children outlined.  Does that answer the question?
