### ISSUE TITLE
Built-in package warns even if URP version is installed.

### ISSUE THREAD

**Issue by seonghwan-dev** [Arvtesh/UnityFx.Outline#37]
This is not a big deal but I prefer to remove unnecessary warning for some inhouse rules.
Is it intended to print warning when URP installed?
If not, I'll PR related to this issue.

Thanks.

```OutlineEffect works with built-in render pipeline only. It does not support SRP (including URP and HDRP).
UnityEngine.Debug:LogWarningFormat (UnityEngine.Object,string,object[])
UnityFx.Outline.OutlineResources:LogSrpNotSupported (UnityEngine.Object) (at Library/PackageCache/com.unityfx.outline@0.8.4/Runtime/Scripts/OutlineResources.cs:497)
UnityFx.Outline.OutlineEffect:Awake () (at Library/PackageCache/com.unityfx.outline@0.8.4/Runtime/Scripts/OutlineEffect.cs:159)
```

![image](https://user-images.githubusercontent.com/79823287/131243254-0a1802c1-99d6-4332-90e3-e2b8690526d3.png)

**Comment by Arvtesh** [comment]
Both `OutlineEffect` and `OutlineBehaviour` are not designed to work with URP. This is what the warning says. Word as intended as far as I can see.

**Comment by seonghwan-dev** [comment]
Oh, I see. Thanks.
