### ISSUE TITLE
HDR Color picker support for OutlineSettings in URP/others

### ISSUE THREAD

**Issue by xXPancakeXx** [Arvtesh/UnityFx.Outline#42]
Hi, could you enable HDR color pickers for the outlines?

I changed it locally for me, but it would be awesome to add this to the repo.
It would only affect the lines 45,192 in OutlineSettingsEditor.cs.
I changed them to the following:
`colorProp.colorValue = EditorGUILayout.ColorField(_colorContent, colorProp.colorValue, true, true, true);`
and for 192:
`colorProp.colorValue = EditorGUI.ColorField(new Rect(rc.x, rc.y + 1 * lineCy, rc.width, EditorGUIUtility.singleLineHeight), _colorContent, colorProp.colorValue, true, true, true);
`

**Comment by Arvtesh** [comment]
I'll look into it, thanks for the suggestion.
