### ISSUE TITLE
Outlines not showing

### ISSUE THREAD

**Issue by LeytonViner** [Arvtesh/UnityFx.Outline#43]
Using PostProcessing outlines. Not showing at all.

**Comment by Arvtesh** [comment]
I'll need more details to help. Unity version, configuration, render pipeline etc.

**Comment by LeytonViner** [comment]
Version: 2021.1.5f
Configuration: Post Processing. Red outline.
Render Pipeline: Default.

**Comment by Arvtesh** [comment]
@LeytonViner is there any additional info on this?
