### ISSUE TITLE
Missing Profiler.EndSample (BeginSample and EndSample count must match): OutlinePass

### ISSUE THREAD

**Issue by Delt06** [Arvtesh/UnityFx.Outline#44]
How to reproduce:
- Open the Outline.URP project
- Open Profiler window
- Look at the console

The console becomes filled with these error messages:
![image](https://user-images.githubusercontent.com/32465621/137641567-6a54fc75-58e4-4105-9b88-c7d1d76035ba.png)
```
Missing Profiler.EndSample (BeginSample and EndSample count must match): OutlinePass
Previous 5 samples:
	RenderTexture.SetActive
	OutlinePass
	Outline-256
	JobAlloc.Grow
	RenderLoop.CleanupNodeQueue
In the scope:
	OutlinePass
	Outline-256
	Render Camera
	UnityEngine.CoreModule.dll!UnityEngine.Rendering::RenderPipelineManager.DoRenderLoop_Internal() [Invoke]
[Invoke]
	PlayerLoop
```

```
Non matching Profiler.EndSample (BeginSample and EndSample count must match): OutlinePass
Previous 5 samples:
	Graphics.DrawProcedural
	RenderTexture.SetActive
	Graphics.DrawProcedural
	RenderTexture.SetActive
	Outline-256
In the scope:
	Outline-256
	Render Camera
	UnityEngine.CoreModule.dll!UnityEngine.Rendering::RenderPipelineManager.DoRenderLoop_Internal() [Invoke]
[Invoke]
	PlayerLoop
	Main Thread
```

Was able to reproduce in the Outline.URP project with 2019.4.17f1 and in a project that imports the package from `npm` with 2020.3.0f1.

**Comment by TheXRMonk** [comment]
> I have the same issue using these packages version:
> 
> ```json
> "com.unityfx.outline": "0.8.4",
> "com.unityfx.outline.urp": "0.4.0",
> ```
> 
> But the issue doesn't exist if I go back to the version **0.3.0** of the `com.unityfx.outline.urp` package. So that's what I did!

Same issue and same solution here as well.

**Comment by Arvtesh** [comment]
Should be fixed in v0.8.5.

**Comment by james-arndt** [comment]
> Should be fixed in v0.8.5.

Not fixed in latest. Issue is appearing on Mac platform, but not on Windows.

**Comment by wmcnamara** [comment]
I am still experiencing this on Unity 6000.0.25f1

**Comment by wmcnamara** [comment]
On Windows

**Comment by wmcnamara** [comment]
![Image](https://github.com/user-attachments/assets/10ab0900-dc38-4da6-aed5-a7a834a57947)
