### ISSUE TITLE
Outline not working in WebGL 1.0 builds

### ISSUE THREAD

**Issue by AGM-GR** [Arvtesh/UnityFx.Outline#45]
Setting Unity project as a WebGl project and the Graphic Api as WebGL 1.0, the outline works on editor but not in build. Also not working with Auto Graphic API in a machine that uses WebGL 1.0 so the problem could be a Shader implementation not compatible with the WebGL 1.0 restrictions.

![imagen](https://user-images.githubusercontent.com/9071269/139411108-6ee221f0-470b-44ca-8da2-a907dc527c36.png)
![imagen](https://user-images.githubusercontent.com/9071269/139412132-afe398ac-c7d9-4300-a5c1-e994a1281d20.png)

Unity: 2020.3.16f1
URP: 10.5.1
UnityFX.Outline: Current repository version (1988f71ed252ed31f3b2a22e604d76337eeb7f91)

Example project: [OutlineWebGl1Bug.zip](https://github.com/Arvtesh/UnityFx.Outline/files/7440733/OutlineWebGl1Bug.zip)

**Comment by Arvtesh** [comment]
I'll take a look, thanks.

**Comment by Arvtesh** [comment]
It's a WebGL 1.0 shader restrictions indeed. In WebGL 1.0 loop index be initialized to a non-constant value. So these lines are the problem:
![image](https://user-images.githubusercontent.com/22732458/141690344-bed337af-2fdc-41f1-aede-2c0ba34f1767.png)
I added the fix.
