### ISSUE TITLE
URP 13+ depth issue turning screen full black (with Fix inside)

### ISSUE THREAD

**Issue by Sir3eBpA** [Arvtesh/UnityFx.Outline#60]
Hi,

I tried running it on Unity 2022.1.19f1 and it worked great except for depth testing, the fix is incredibly simple, you have to swap out the RTHandle for depth texture from custom made one to the **cameraDepthTargetHandle** provided by URP.

Looks like this:
![2](https://user-images.githubusercontent.com/10902756/200152702-7846ea1f-2f0c-4978-bf3f-1dd76e6ec820.png)

Essentially replacing line 52 in **OutlinePass** in the URP folder. I've done this in my fork so feel free to check it out here [CLICK](https://github.com/Sir3eBpA/UnityFx.Outline/commit/e4baa9684b04c27c8e63110d7541657ec740448f#diff-3a1e627a2390c6a937e3a4874bd456cfa4fc31089ae861734262c7d793299573)

and here's the final result:
![1](https://user-images.githubusercontent.com/10902756/200152593-dfa087ca-1ec9-4006-8638-7d7c3354c3f6.png)

Hope anyone finds it useful!

Don't want to make a pull request for it as it changes the URP and unity versions so this is not a proper fix for everyone but for those who suffer from the same issues I did 😄

**Comment by CaseyHofland** [comment]
The proposed solution here is incompatible with MSAA, use the solution proposed in the Pull Request for MSAA compatible outlines once more.
