### ISSUE TITLE
Missing Profiler.EndSample (Every BeginSample call must have a subsequent EndSample call within the same frame): OutlinePass

### ISSUE THREAD

**Issue by michael811125** [Arvtesh/UnityFx.Outline#70]
![image](https://github.com/Arvtesh/UnityFx.Outline/assets/30960759/1e977250-a6fc-4b4e-a995-e7fdd0228b4d)

When I open profile will occured missing Profiler.EndSample issue, how do i resolve it?

**Comment by james-arndt** [comment]
Is this on a Windows machine or do you see these errors on a Mac?

**Comment by michael811125** [comment]
> Is this on a Windows machine or do you see these errors on a Mac?

I dev on windows.

**Comment by james-arndt** [comment]
Rolling back the package to -> "com.unityfx.outline.urp": "0.3.0"  in the manifest is what fixed this error for us. It didn't adversely affect any of the rendering or functionality.

**Comment by michael811125** [comment]
> Rolling back the package to -> "com.unityfx.outline.urp": "0.3.0" in the manifest is what fixed this error for us. It didn't adversely affect any of the rendering or functionality.

ok I will try, thank you.
